# GPU-accelerated KLT Makefile
CC = gcc
NVCC = nvcc
ARCH = sm_75

.PHONY: all clean run profile

all: example3_gpu

example3_gpu: libklt_gpu.a
	$(NVCC) -arch=$(ARCH) -O3 -o example3_gpu example3.c -L. -lklt_gpu -lm

libklt_gpu.a: cpu_objs gpu_objs
	ar ruv libklt_gpu.a *.o

cpu_objs:
	$(CC) -c -DNDEBUG -O3 error.c pnmio.c pyramid.c storeFeatures.c klt.c klt_util.c writeFeatures.c

gpu_objs:
	$(NVCC) -c -arch=$(ARCH) -O3 convole.cu trackfeatures.cu selectGoodFeatures.cu gpu_memory_pool.cu

run: example3_gpu
	LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/cuda-12/lib64:$$LD_LIBRARY_PATH ./example3_gpu

profile: example3_gpu
	LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/cuda-12/lib64:$$LD_LIBRARY_PATH nsys profile -o klt_gpu_profile --stats=true ./example3_gpu
	nsys stats --force-export=true klt_gpu_profile.nsys-rep > klt_gpu_stats.txt

clean:
	rm -f *.o libklt_gpu.a example3_gpu klt_gpu_profile* klt_gpu_stats.txt *.sqlite feat*.ppm features.*
