# GPU-accelerated KLT Makefile (Colab-optimized)
CC = gcc
NVCC = nvcc
ARCH = sm_75

.PHONY: all clean run profile

all: example3_gpu

example3_gpu: libklt_gpu.a
	$(NVCC) -arch=$(ARCH) -O3 -o example3_gpu example3.c -L. -lklt_gpu -lm

libklt_gpu.a: cpu_objs gpu_objs
	ar ruv libklt_gpu.a *.o

cpu_objs:
	$(CC) -c -DNDEBUG -O3 error.c pnmio.c pyramid.c storeFeatures.c klt.c klt_util.c writeFeatures.c

gpu_objs:
	$(NVCC) -c -arch=$(ARCH) -O3 convolve.cu trackFeatures.cu selectGoodFeatures.cu

run: example3_gpu
	./example3_gpu

profile: example3_gpu
	nvprof --print-gpu-trace --print-api-trace ./example3_gpu > klt_gpu_profile.txt 2>&1

clean:
	rm -f *.o libklt_gpu.a example3_gpu klt_gpu_profile* klt_gpu_stats.txt *.sqlite
